version: "1"
services:
  - type: web
    name: ganza-ai-backend-sovereign-final
    env: python
    plan: free
    rootDirectory: gemini/multimodal-live-api/native-audio-websocket-demo-apps/react-demo-app
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py
